version: 2
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/gcrunpresso/
    binary: gcrunpresso
    tags:
      - no_azurerm
      - no_s3
    ldflags:
      - -s -w
      - -X github.com/kayac/gcrunpresso/v2.Version=v{{.Version}}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
release:
  prerelease: auto
  use_existing_draft: true
archives:
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ .Env.NIGHTLY_VERSION }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
