name: test action
on:
  push:
    branches:
      - v2
  pull_request:
  workflow_dispatch:

jobs:
  test_action:
    strategy:
      matrix:
        runner:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    name: test action
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          version: latest
      - run: |
          gcrunpresso version 2>&1 | fgrep "gcrunpresso"
